### ISSUE TITLE
Python 3.5 (on Ubuntu 16.04) is old and needs to be replaced

### ISSUE THREAD

**Issue by kobusan** [PKSHATechnology-Research/tdmelodic#2]
`sys.stderr.write(f"ERROR: {exc}")` Error after upgrade pip.

```bash
root@246c85607a6c:~/workspace# python3 -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 888kB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-21.0.1
root@246c85607a6c:~/workspace# python3 -m pip install --upgrade setuptools
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
```

**Comment by tachi-hi** [comment]
Thank you for your report. I will fix it.

**Comment by tachi-hi** [comment]
75b79bed7d5da612da697e3c1b0a792ba0a70584
I have updated the Dockerfile. It seems working in my environment.
Please try it out.

**Comment by tachi-hi** [comment]
https://github.com/PKSHATechnology-Research/tdmelodic/commit/8a1ee9f4cbf4c86bc034a1fc9d57cd3476580a45
Created a CI for docker build with github actions. It will run once every two months.
