### ISSUE TITLE
Dockerビルド後、Mecab初期化処理時点で [pos != std::string::npos] format error が発生する

### ISSUE THREAD

**Issue by RoloAfrole** [PKSHATechnology-Research/tdmelodic#25]
[docker イメージをビルド](https://tdmelodic.readthedocs.io/ja/latest/pages/docker.html)に記載がある通りにdockerイメージをビルドしたあと動作確認として下記コマンドを実行すると[pos != std::string::npos] format error が発生しうまく動作しないようです。
```
from tdmelodic.nn.lang.mecab.unidic import UniDic
u = UniDic()
```

下記は実行結果です。

```
> docker run -it --rm tdmelodic:latest
root@d987ad349980:~/workspace# echo 深層学習 | mecab -d `mecab-config --dicdir`/unidic
深層    シンソー        シンソウ        深層    名詞-普通名詞-一般                      0
学習    ガクシュー      ガクシュウ      学習    名詞-普通名詞-サ変可能                  0
EOS
root@d987ad349980:~/workspace# python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tdmelodic.nn.lang.mecab.unidic import UniDic
>>> u = UniDic()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/MeCab/__init__.py", line 137, in __init__
    super(Tagger, self).__init__(args)
RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tdmelodic/nn/lang/mecab/unidic.py", line 69, in __init__
    self.__init_mecab()
  File "/usr/local/lib/python3.8/dist-packages/tdmelodic/nn/lang/mecab/unidic.py", line 72, in __init_mecab
    self.unidic_acc = MeCab.Tagger(
  File "/usr/local/lib/python3.8/dist-packages/MeCab/__init__.py", line 139, in __init__
    raise RuntimeError(error_info(rawargs)) from ee
RuntimeError:
----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: -d /usr/lib/x86_64-linux-gnu/mecab/dic/unidic -r /usr/local/lib/python3.8/dist-packages/tdmelodic/nn/lang/mecab/my_mecabrc -Oacc
default dictionary path: None
[pos != std::string::npos] format error:
----------------------------------------------------------

>>>
```

Mecabの初期化段階でエラーが起きているようで、
docker内で`echo 深層学習 | mecab -d /usr/lib/x86_64-linux-gnu/mecab/dic/unidic -r /usr/local/lib/python3.8/dist-packages/tdmelodic/nn/lang/mecab/my_mecabrc -Oacc`を直接実行すると同様に`[pos != std::string::npos] format error`が発生します。``echo 深層学習 | mecab -d /usr/lib/x86_64-linux-gnu/mecab/dic/unidic `だけだと動作します。

詳しくないため調べた限りでは指定しているリソースファイル内の定義方法が間違っているではと思います。

**Comment by RoloAfrole** [comment]
windows環境でdockerビルドしているためかはわかりませんが、
tdmelodic/nn/lang/mecab/my_mecabrc
がCRLFで改行しているためにエラーが起きていました。
LFで改行にすれば動作しました。
